-- MySQL Script generated by MySQL Workbench
-- Tue Apr 14 12:30:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ishop
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ishop` ;

-- -----------------------------------------------------
-- Schema ishop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ishop` DEFAULT CHARACTER SET utf8 ;
USE `ishop` ;

-- -----------------------------------------------------
-- Table `ishop`.`DICT_USERS_STATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`DICT_USERS_STATE` ;

CREATE TABLE IF NOT EXISTS `ishop`.`DICT_USERS_STATE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(128) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`USERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`USERS` ;

CREATE TABLE IF NOT EXISTS `ishop`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `LOGIN` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(45) NULL,
  `NAME` VARCHAR(45) NULL,
  `SURNAME` VARCHAR(45) NULL,
  `PHONE` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `ADDRESS` VARCHAR(255) NULL,
  `DATE_OF_BIRTH` DATE NULL,
  `STATE_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_users_status_id_idx` (`STATE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_users_status_id`
    FOREIGN KEY (`STATE_ID`)
    REFERENCES `ishop`.`DICT_USERS_STATE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`ROLES` ;

CREATE TABLE IF NOT EXISTS `ishop`.`ROLES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DESCRIPTION` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`CATEGORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`CATEGORY` ;

CREATE TABLE IF NOT EXISTS `ishop`.`CATEGORY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `CATEGORY_NAME` VARCHAR(45) NULL,
  `CATEGORY_DESC` VARCHAR(1024) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`DICT_ITEMS_STATE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`DICT_ITEMS_STATE` ;

CREATE TABLE IF NOT EXISTS `ishop`.`DICT_ITEMS_STATE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(128) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`ITEMS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`ITEMS` ;

CREATE TABLE IF NOT EXISTS `ishop`.`ITEMS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ID_CATEGORY` INT NULL,
  `NAME_SHORT` VARCHAR(45) NULL,
  `NAME_FULL` VARCHAR(255) NULL,
  `DESCRIPTION` VARCHAR(1024) NULL,
  `MANUFACTURER` VARCHAR(255) NULL,
  `PRICE` DECIMAL(10,2) NULL,
  `IMAGE_ID` INT NULL,
  `STATE_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_categoty_id_idx` (`ID_CATEGORY` ASC) VISIBLE,
  INDEX `fk_items_state_id_idx` (`STATE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_categoty_id`
    FOREIGN KEY (`ID_CATEGORY`)
    REFERENCES `ishop`.`CATEGORY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_state_id`
    FOREIGN KEY (`STATE_ID`)
    REFERENCES `ishop`.`DICT_ITEMS_STATE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`STORAGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`STORAGE` ;

CREATE TABLE IF NOT EXISTS `ishop`.`STORAGE` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ITEM_ID` INT NULL,
  `COUNT` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_item_id_idx` (`ITEM_ID` ASC) VISIBLE,
  CONSTRAINT `fk_item_id`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `ishop`.`ITEMS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`DICT_PAYMENT_TYPES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`DICT_PAYMENT_TYPES` ;

CREATE TABLE IF NOT EXISTS `ishop`.`DICT_PAYMENT_TYPES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(45) NULL,
  `DESCRIPTION` VARCHAR(1024) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`ORDERS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`ORDERS` ;

CREATE TABLE IF NOT EXISTS `ishop`.`ORDERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `START_DATE` DATETIME NULL,
  `USER_ID` INT NULL,
  `PAYMENT_TYPE_ID` INT NULL,
  `COMMENT` VARCHAR(255) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_user_id_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_payment_type_id_idx` (`PAYMENT_TYPE_ID` ASC) VISIBLE,
  CONSTRAINT `fk_orders_user_id`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `ishop`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_payment_type_id`
    FOREIGN KEY (`PAYMENT_TYPE_ID`)
    REFERENCES `ishop`.`DICT_PAYMENT_TYPES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`DICT_ORDER_STATUS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`DICT_ORDER_STATUS` ;

CREATE TABLE IF NOT EXISTS `ishop`.`DICT_ORDER_STATUS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `STATUS_NAME` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`ITEM_REVIEWS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`ITEM_REVIEWS` ;

CREATE TABLE IF NOT EXISTS `ishop`.`ITEM_REVIEWS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `USER_ID` INT NULL,
  `ITEM_ID` INT NULL,
  `RATE` INT NULL,
  `TEXT` VARCHAR(1024) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_user_id_idx` (`USER_ID` ASC) VISIBLE,
  INDEX `fk_reviews_item_id_idx` (`ITEM_ID` ASC) VISIBLE,
  CONSTRAINT `fk_rewiews_user_id`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `ishop`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviews_item_id`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `ishop`.`ITEMS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`ORDER_STATUS_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`ORDER_STATUS_HISTORY` ;

CREATE TABLE IF NOT EXISTS `ishop`.`ORDER_STATUS_HISTORY` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `EVENT_DATE` DATETIME NULL,
  `ORDER_ID` INT NULL,
  `ORDER_STATUS` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_hst_order_id_idx` (`ORDER_ID` ASC) VISIBLE,
  INDEX `fk_hst_status_id_idx` (`ORDER_STATUS` ASC) VISIBLE,
  CONSTRAINT `fk_hst_order_id`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `ishop`.`ORDERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_hst_status_id`
    FOREIGN KEY (`ORDER_STATUS`)
    REFERENCES `ishop`.`DICT_ORDER_STATUS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`IMAGES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`IMAGES` ;

CREATE TABLE IF NOT EXISTS `ishop`.`IMAGES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ITEMS_ID` INT NULL,
  `IMG` BLOB NULL,
  PRIMARY KEY (`ID`),
  INDEX `images_items_id_idx` (`ITEMS_ID` ASC) VISIBLE,
  CONSTRAINT `images_items_id`
    FOREIGN KEY (`ITEMS_ID`)
    REFERENCES `ishop`.`ITEMS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`ORDER_DETAILS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`ORDER_DETAILS` ;

CREATE TABLE IF NOT EXISTS `ishop`.`ORDER_DETAILS` (
  `ORDER_ID` INT NULL,
  `ITEM_ID` INT NULL,
  `COUNT` INT NULL,
  `ITEM_COST` DECIMAL(10,2) NULL,
  INDEX `order_det_item_id_idx` (`ITEM_ID` ASC) VISIBLE,
  INDEX `order_det_order_id_idx` (`ORDER_ID` ASC) VISIBLE,
  CONSTRAINT `order_det_item_id`
    FOREIGN KEY (`ITEM_ID`)
    REFERENCES `ishop`.`ITEMS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `order_det_order_id`
    FOREIGN KEY (`ORDER_ID`)
    REFERENCES `ishop`.`ORDERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ishop`.`USER_ROLES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ishop`.`USER_ROLES` ;

CREATE TABLE IF NOT EXISTS `ishop`.`USER_ROLES` (
  `USER_ID` INT NULL,
  `ROLE_ID` INT NULL,
  INDEX `fk_user_roles_role_id_idx` (`ROLE_ID` ASC) VISIBLE,
  INDEX `fk_user_roles_user_id_idx` (`USER_ID` ASC) VISIBLE,
  CONSTRAINT `fk_user_roles_role_id`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `ishop`.`ROLES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_roles_user_id`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `ishop`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;




--


ALTER TABLE `ishop`.`users` 
ADD UNIQUE INDEX `LOGIN_UNIQUE` (`LOGIN` ASC) VISIBLE,
ADD UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE;
;